### ISSUE TITLE
ModuleNotFoundError: No module named

### ISSUE THREAD

**Issue by 1abu83** [flet-dev/flet#3356]
Traceback (most recent call last):
  File "<string>", line 43, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\REDMI\AppData\Local\Temp\serious_python_temp79c3a171\main.py", line 2, in <module>
ModuleNotFoundError: No module named 'requests'

**Comment by Yagniksojitra** [comment]
Use httpx, it will work. I had similar issue with apk build. Solved it using httpx.

**Comment by ndonkoHenri** [comment]
I think adding `requests` to your requirements file should solve this.

**Comment by Pomurnik** [comment]
I have requests in pyproject.toml (tried also with requirements.txt) and still have a issue. But in build/site-packages i see requests foler for every platform.
