### ISSUE TITLE
Clipboard not storing text on iOS devices

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#423]
**Description**
The clipboard functionality is not working on iPhone OS devices. 

**Code example to reproduce the issue:**
Flet-Colors-Browser repo: https://github.com/ndonkoHenri/Flet-Color-Browser
Browser Link: https://flet-colors-browser.fly.dev/

**Describe the results you received:**
When a container is clicked, a function(in the code) is called, which copies the container's text value(a color code) to the clipboard. The clipboard doesn't seem to store copied text. We noticed this only on iOS devices for now.

**Describe the results you expected:**
I expect the clipboard to store the color code of a container, when this container is clicked and later on allow the user have the possibility to paste the copied text(color code) anywhere. (clipboard's basic functionalities)

**Additional information:**
This behavior was only noticed on iOS(for now).
On MacOS and Windows we don't have this issue.

This same Clipboard issue has also been noticed when using https://flet-icons-browser.fly.dev/ on iOS.

**Flet version**:
Flet 0.1.60 (latest)

**Comment by ndonkoHenri** [comment]
Note: This bug is just on iOS devices.
Everything works fine on Androids.

**Comment by FeodorFitsner** [comment]
I'm testing it on iOS and I'm getting these errors in web inspector when clicking on a color and attempting to send data to a clipboard:

```
[Log] copy is not successful NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. (main.dart.js, line 28885)
[Error] 
	(anonymous function) (main.dart.js:4928)
[Log] copy is not successful NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. (main.dart.js, line 28885)
[Error] 
	(anonymous function) (main.dart.js:4928)
```

![image](https://user-images.githubusercontent.com/5041459/193654844-f691327e-7405-430c-a9d3-4010cb6df6fa.png)

Could you try on your side please? This article helps: https://www.lifewire.com/activate-the-debug-console-in-safari-445798

**Comment by FeodorFitsner** [comment]
It doesn't work in desktop Safari as well, with the same error.

**Comment by ndonkoHenri** [comment]
On which device should I try? 
I am having just IPhone and a Win PC at the moment.

With the Windows10PC, everything works fine..(on browser and App)

**Comment by hololeo** [comment]
it works on mac /chrome for me

**Comment by FeodorFitsner** [comment]
Never mind, looks like the issue is deeper than just a browser. It depends on *how* do you call clipboard API 😳 and on Safari it should follow a gesture. I'm investigating.

**Comment by ndonkoHenri** [comment]
Wow.

**Comment by ndonkoHenri** [comment]
Please send any useful link. I like reading and learning more about stuffs.

**Comment by FeodorFitsner** [comment]
From here: https://webkit.org/blog/10855/async-clipboard-api/

The request to write to the clipboard must be triggered during a user gesture. A call to clipboard.write or clipboard.writeText outside the scope of a user gesture (such as "click" or "touch" event handlers) will result in the immediate rejection of the promise returned by the API call.

There are more articles about that "feature" if you google.

**Comment by ndonkoHenri** [comment]
Did you happen to resolve the issue @FeodorFitsner ?

**Comment by FeodorFitsner** [comment]
Yep, fixed in the last release.

**Comment by ndonkoHenri** [comment]
Great Job Commander.
I will give it a check.

**Comment by ndonkoHenri** [comment]
The Clipboard seems still not to be working on my iPhone.
I will open a new issue
