### ISSUE TITLE
Badge property and Map Control not working on Android 

### ISSUE THREAD

**Issue by Siva-Rajan-R** [flet-dev/flet#4362]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

badge,
After updation of flet==0.25.dev3717 the badge property is added to every controls and i tried it .it works fine on Windows but,It was not working on Android 

Map,
The map Control works fine on both windows and android before updating flet==0.25.0.dev3717.but after update its only work on Windows not on Android

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

1.Fix the badge property to work on Android
2.Fix the Map to work on Android 

### Expected behavior

Badge and map wants to work on Android properly

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]
![IMG-20241113-WA0005](https://github.com/user-attachments/assets/27cd0641-180a-42ab-84ae-8df4acc0db64)
![IMG-20241113-WA0004](https://github.com/user-attachments/assets/19755631-357c-4470-93a9-ef626a326ad5)
![Screenshot_2024-11-12-23-18-10-19_b3c61c1ad2a7062e9ad6b926200ddbc2](https://github.com/user-attachments/assets/cc149d55-c32b-4e1c-9c2c-962cb09dbfb7)
![Screenshot_2024-11-12-23-13-21-11_b3c61c1ad2a7062e9ad6b926200ddbc2](https://github.com/user-attachments/assets/d9b6cd36-2035-4030-a94e-aed8ef512f72)
</details>

### Operating System

Windows

### Operating system details

windows 11

### Flet version

0.25.0.dev3717

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Additional details

It works on flet==0.24.1

**Comment by ndonkoHenri** [comment]
Can you share your requirements file?
Make sure you set the right Flet version in it.

**Comment by Siva-Rajan-R** [comment]
@ndonkoHenri 
flet==0.25.0.dev3717
websockets==14.0
requests==2.32.3
pytz==2024.2

this is my requirements.txt

**Comment by Siva-Rajan-R** [comment]
@ndonkoHenri 
Not only badge , the map Control also not working as we expected on Android

**Comment by JCxOx** [comment]
Hello Siva-Rajan-R,

I have the same problem with map on Android.
The app works correctly on Linux and web, but nothing is displayed on Android (map frame always gray).

Have you found a solution ?

I have no requirements.txt , do you think I need to add websockets==14.0 or requests==2.32.3 or other ...
or any permission ?

Thanks,
JC

**Comment by Siva-Rajan-R** [comment]
@JCxOx 

You don't need to add the websockets==14.0 or requests==2.32.3 or other It was an bug on packaging the flet team will resolve it as soon as possible. We need to wait for it🙂 and also don't forgot to add flet build apk --include-packages flet_map while building an apk , in future.

**Comment by JCxOx** [comment]
Hello Siva-Rajan-R,

Thanks for the advices, I am not familiar with specific Android setting.
I will wait for the new flet version.

JC

**Comment by ndonkoHenri** [comment]
Please retry with the new flet v0.25.0. 
It should be fixed now.

**Comment by JCxOx** [comment]
Hello ndonkoHenri, 

I have updated the new version (with $ pip install flet)
Now my flet version is 0.25.0   (no more 0.25.0.dev3750)

But unfortunatly nothing works !
Even the desktop version has an error : AttributeError: module 'flet.map' has no attribute 'MapConfiguration'

Maybe I didn't update flet correctly...

Thanks,
JC

**Comment by JCxOx** [comment]
Hello,

After removing the map.MapConfiguration( ... )  line, I put the initial_center=    and   initial_zoom= outside and that works on the desktop computer (linux).
But the Android is still not working. 
I build the APK with the following command : flet build apk --include-packages flet_map

The building process is OK : Successfully built your .apk for Android! ....

But on my Android phone, there is many error :

Traceback (most recent call last):
  File "<string>", line 47, in <module>
  File "<frozen runpy>", line 222, in run_module
  File "<frozen runpy>", line 142, in _get_module_details
ImportError: No module named main

With the previous flet version (0.25.0.dev3750) that was Ok, no error ... but no map ...

Thanks for your help,

JC

**Comment by FeodorFitsner** [comment]
Should be fixed now. Please re-build the app.

**Comment by JCxOx** [comment]
Hello,

I have updated flet with :$ pip install flet --force-reinstall

and re-built the App :$ flet build apk --include-packages flet_map

but the same error appears :

Traceback (most recent call last):
File "", line 47, in
File "", line 222, in run_module
File "", line 142, in _get_module_details
ImportError: No module named main

**Comment by ndonkoHenri** [comment]
I will suggest you create a new venv and install Flet from scratch, making sure to modify the flet version in your requirements/pyproject file to the latest equally.

**Comment by JCxOx** [comment]
Ok thanks, I will try asap,
