### ISSUE TITLE
bug: VerticalDivider   Dragging is very sluggish. Both v1 and 0.28.3 are very sluggish

### ISSUE THREAD

**Issue by yst-one** [flet-dev/flet#5625]
### Duplicate Check

- [x] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

https://github.com/user-attachments/assets/40643be0-34c4-44ce-9de9-11f2fb8f30f9

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft
class Search(ft.Container):
    def __init__(self):
        super().__init__()

        def close_f(e):
            self.close_bt.visible=False
            self.tf.value=""
            self.update()
        self.close_bt=ft.IconButton(icon=ft.Icons.CLOSE,icon_size=15,
                                    on_click=close_f,hover_color=ft.Colors.TRANSPARENT,)

        self.tf=ft.TextField(prefix_icon=ft.IconButton(ft.Icons.SEARCH,hover_color=ft.Colors.TRANSPARENT,icon_size=15,),
                                    suffix_icon=self.close_bt,
                                    hint_text="搜索",
                                    text_size=12,
                                    text_style=ft.TextStyle(height=0.5),
                                    filled=False,
                                    border_width=1,
                                    border_color=ft.Colors.TRANSPARENT,
                                    on_blur=self.search_blur,
                                    on_focus=self.search_focus,
                                    height=30,
                                    cursor_height=15,
                                    cursor_width=1,
                                    cursor_color=ft.Colors.BLUE,
                                    focused_border_color=ft.Colors.BLUE,

                                    
                                    )
        
        self.add_bt = ft.IconButton(icon=ft.Icons.ADD,width=30,height=30,icon_size=15,
                                    
                                    style=ft.ButtonStyle(
                                        bgcolor={ft.ControlState.FOCUSED: ft.Colors.PINK_200, "": ft.Colors.GREY_200},
                                        shape={

                                            ft.ControlState.DEFAULT:ft.RoundedRectangleBorder(radius=2),
                                        }
                                    ),
                                    on_click= lambda e : print(e)
                                    )
      
    def search_blur(self,e):
         self.close_bt.visible=False
         e.control.hint_text="搜索",
         self.update()
         print(e)
    
    def search_focus(self,e):
        self.close_bt.visible=True
        e.control.hint_text="",
        self.update()
        print(e)

    def build(self):
        self.content=ft.Row(controls=[
                 
                ft.Container(bgcolor=ft.Colors.GREY_200,
                            border_radius=2,
                            content=self.tf,
                            expand=True
                ),
                self.add_bt,
                       
        ])
       




class ChatList(ft.Container):
    def __init__(self):
        super().__init__()
        self.padding=ft.padding.only(top=20,left=10,right=10,bottom=10)
        self.border_radius=1
        self.width=300
 
    
    def build(self):
        self.content=ft.Column(controls=[
            Search(),
            ft.Stack(expand=True,controls=[
                ft.ListView(
                    controls=[
                        ft.ListTile(
                                height=70,
                                hover_color=ft.Colors.GREY_100,
                                leading=ft.Icon(ft.Icons.SNOOZE,size=50),
                                title=ft.Text(
                                    "Two-line with leading and trailing controls",
                                    overflow=ft.TextOverflow.ELLIPSIS
                                ),
                                subtitle=ft.Text("Here is a second title.",overflow=ft.TextOverflow.ELLIPSIS),
                                on_click= lambda e : print(e),
                            
                                
                            ) for i in range(300) 
                        ]
                ) ,
            ]),
        ])


class ChatPage(ft.Row):
    def __init__(self,page: ft.Page):
        super().__init__(expand=True)
        chat_list =ChatList()

        def move_vertical_divider(e: ft.DragUpdateEvent):
            if (e.local_delta.x > 0 and chat_list.width < 360) or (e.local_delta.x < 0 and chat_list.width > 100):
                chat_list.width += e.local_delta.x
            chat_list.update()

        def show_draggable_cursor(e: ft.HoverEvent):
            e.control.mouse_cursor = ft.MouseCursor.RESIZE_LEFT_RIGHT
            e.control.update()
            cl=ChatList()


        self.controls=[chat_list,ft.GestureDetector(
                content=ft.VerticalDivider(),
                drag_interval=10,
                on_pan_update=move_vertical_divider,
                on_hover=show_draggable_cursor,
            ),ft.Container(bgcolor=ft.Colors.GREEN,expand=True)]

        page.theme= ft.Theme(

        )
        page.bgcolor=ft.Colors.WHITE
        page.add(self)
    def will_unmount(self):
        print("ChatPage will unmount")
        return super().will_unmount()
    
    def did_mount(self):
        print("ChatPage did mount")
        return super().did_mount()
    
    
if __name__ ==  '__main__':
    ft.run(ChatPage)
```

</details>

### To reproduce

s

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

11

### Flet version

0.28.3 or V1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by yst-one** [comment]
https://github.com/user-attachments/assets/a0d3131c-2dd7-48ec-9794-2b3f1c9d6a1f

**Comment by yst-one** [comment]
> 0.28.3.mp4

this is 0.28.3

**Comment by FeodorFitsner** [comment]
I tested it on 1.0 and it worked smoothly, but (!) I disabled page auto-update (which is kinda experimental feature):

```py
import flet as ft

ft.context.disable_auto_update()


class Search(ft.Container):
    def __init__(self):

...
```

It's 1.0-only feature.

The result:

https://github.com/user-attachments/assets/8014e459-b2c2-4cee-bce5-1b8e00b71e75

It's on macOS though.

Have you tried running in the browser?

**Comment by yst-one** [comment]
I added `ft.context.disable_auto_update()` to the code, but the performance on Windows 11 or the web remained equally slow.

**Comment by yst-one** [comment]
https://github.com/user-attachments/assets/8fa85f5e-37c8-4399-8a9d-c9a2f6864816

**Comment by yst-one** [comment]
Also set e.ontrol.hint text=" search ", the 0.28.3  Correct  value will be wrapped by (",), and v1 will be wrapped by []  

<img width="298" height="62" alt="Image" src="https://github.com/user-attachments/assets/3727565c-6aec-4efb-a96a-f563ccc307ba" />

**Comment by FeodorFitsner** [comment]
For the sake of experiment, try reducing the number of items in the list to see if that helps.

**Comment by yst-one** [comment]
> For the sake of experiment, try reducing the number of items in the list to see if that helps.

I have tried that reducing the number of Listtiles can avoid slowness, but the features of listView should be able to support large list data

**Comment by FeodorFitsner** [comment]
Ok, for web testing - what browser do you use?

**Comment by yst-one** [comment]
bacause  build_controls_on_demand defualt

> Ok, for web testing - what browser do you use?
edge  140.0.3485.54

**Comment by FeodorFitsner** [comment]
OK, will be investigating.

**Comment by FeodorFitsner** [comment]
Try commenting this ButtonStyle:

<img width="650" height="423" alt="Image" src="https://github.com/user-attachments/assets/44b0ad77-070a-4840-85de-f71d3cbd68dc" />

**Comment by yst-one** [comment]
> Try commenting this ButtonStyle:尝试注释此 ButtonStyle：
> 
> <img alt="Image" width="650" height="423" src="https://private-user-images.githubusercontent.com/5041459/487066963-44b0ad77-070a-4840-85de-f71d3cbd68dc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTczODkzMjAsIm5iZiI6MTc1NzM4OTAyMCwicGF0aCI6Ii81MDQxNDU5LzQ4NzA2Njk2My00NGIwYWQ3Ny0wNzBhLTQ4NDAtODVkZS1mNzFkM2NiZDY4ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MDlUMDMzNzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWU4NTZiNmM3MmQ1ZGZmOWFmNWUwMjMyNmJhYTRjNjhiMDk4M2Y4OWI1NjU0YTRiZGI0ZTg2OGU0ZTMwMTMxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.a-ciQHzBGqWgTs5b2J2_SKinLPltaUXEukKN0gELWuE">

It's annotated, but it's still as slow as ever

**Comment by yst-one** [comment]
After I made the annotations, the operation was still as slow as ever

**Comment by yst-one** [comment]
Another minor bug has been discovered. When I select the listview item and modify its background color, it appears abnormally black. This problem only occurs when the software is opened for the first time
```python
class ChatList(ft.Container):
    def __init__(self):
        super().__init__()
        self.padding=ft.padding.only(top=20,left=10,right=0,bottom=10)
        self.border_radius=1
        self.width=300
        # self.expand=3
        self.search_page=SearchPage()
        self.search_page.visible=False
        self.search_bar =SearchBar(self.search_page),

       
 
    
    def build(self):
        self.content=ft.Column(controls=[
            SearchBar(self.search_page),
            ft.Stack(expand=True,controls=[
                ft.ListView(
                    controls=[
                        ft.ListTile(
                                height=70,
                                mouse_cursor=ft.MouseCursor.BASIC,
                                hover_color=ft.Colors.GREY_100,
                                leading=ft.Icon(ft.Icons.SNOOZE,size=40),
                                title=ft.Text(
                                    "Two-line with leading and trailing controls",
                                    overflow=ft.TextOverflow.ELLIPSIS
                                ),
                                subtitle=ft.Text("Here is a second title.",overflow=ft.TextOverflow.ELLIPSIS),
                                on_click= self.list_on_click ,
                                
                            ) for i in range(300)
                        ]
                ) ,
            self.search_page,    
            ]),

        ])
    
    def list_on_click(self,e: ft.ControlEvent):
        
        for control in e.control.parent.controls:
            control.bgcolor=ft.Colors.WHITE
            control.hover_color=ft.Colors.GREY_100,
        e.control.bgcolor=ft.Colors.BLUE_100
        self.update()


```

**Comment by yst-one** [comment]
https://github.com/user-attachments/assets/35fed0c5-6906-4517-be31-76ec1cfad474

**Comment by yst-one** [comment]
There's another issue. The on focus and on blur functions of iconButton haven't taken effect. I want to use these two features to create a popover. I have no other ideas except this.

**Comment by yst-one** [comment]
> There's another issue. The on focus and on blur functions of iconButton haven't taken effect. I want to use these two features to create a popover. I have no other ideas except this.

https://github.com/user-attachments/assets/f33421c3-fafe-4d8e-bf3d-7973fbbc04e0
like this

**Comment by FeodorFitsner** [comment]
There was a regression in on-demand building of ListView items, so, basically, the list widget was rebuilding children every time.

It's fixed in the latest pre-release of Flet v1 - please upgrade and give it another try.

In general, upon my testing, Windows rendering is still lacking compared to other platforms, especially those ones already using Impeller. Good news - Impeller is coming to Windows (soon). I saw it's been already added for Windows in `master` channel.

A few optimization notes:

1. Set both `ListView.item_extent` and `ListTile.height` - that improves rendering performance as Flutter can better calculate dimensions:

```py
...
                        ft.ListView(
                            item_extent=70,
                            controls=[
                                ft.ListTile(
                                    key=i,
                                    height=70,
                                    hover_color=ft.Colors.GREY_100,
                                    leading=ft.Icon(ft.Icons.SNOOZE, size=50),
                                    title=ft.Text(
                                        f"{i} Two-line with leading and trailing controls",
                                        overflow=ft.TextOverflow.ELLIPSIS,
                                    ),
                                    subtitle=ft.Text(
                                        "Here is a second title.",
                                        overflow=ft.TextOverflow.ELLIPSIS,
                                    ),
                                    on_click=lambda e: print(e),
                                )
...
```

2. Set `ListTile.key` to a distinct value - that optimizes re-drawls too.
3. Try using some other control instead of ListView. People say ListView could be a bit expensive. For example, you can easily fake ListView with Container:

```py
...
                                ft.Container(
                                    ft.Text(f"{i} An Item with ListView"),
                                    key=i,
                                    alignment=ft.Alignment.CENTER_LEFT,
                                    padding=10,
                                    ink=True,
                                    on_click=lambda e: print(e),
                                )
                                for i in range(300)
...
```

Hope that helps.

**Comment by yst-one** [comment]
Thank you very much. I tried the latest version, but the effect wasn't very obvious and it was still slow. Besides, the following problem still exists

> listtile.bgcolor.appears.abnormally.black.mp4

**Comment by yst-one** [comment]
https://github.com/user-attachments/assets/05a8852d-b33f-4962-9371-4b74a4ce4375

<img width="136" height="20" alt="Image" src="https://github.com/user-attachments/assets/c9ae435e-8a42-42f7-b6b9-457c51916926" />
